mynote/mynote/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mynote.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^$', include('notes.urls')),
    url(r'^notes/', include('notes.urls', namespace="notes")),
    url(r'^admin/', include(admin.site.urls)),

)

mynote/notes/urls.py
__author__ = 'prabhugs'

from django.conf.urls import patterns, url

from notes import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='index'),
                       url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
                       url(r'^(?P<pk>\d+)/comments/$', views.CommentsView.as_view(), name='comments'),
                       url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
                       url(r'^(?P<post_id>\d+)/comment/$', views.comment, name='comment'),
                       )

mynote/notes/models.py
from django.db import models

import datetime
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    def __str__(self):
        return self.post_text

    post_text = models.CharField(max_length=500)
    published_date = models.DateTimeField('published on')

    def waspublishedrecently(self):
        return timezone.datetime.now() >= self.published_date >= timezone.datetime.now() - datetime.timedelta(days=1)

class Comment(models.Model):
    def __str__(self):
        return self.comment_text

    post = models.ForeignKey(Post)
    comment_text = models.CharField(max_length=500)
    comment_like = models.IntegerField(default=0)
    commented_date = models.DateTimeField('commented on')

mynote/notes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
#from django.template import RequestContext, loader

from notes.models import Post, Comment


# Create your views here.

class IndexView(generic.ListView):
    template_name = "notes/index.html"
    context_object_name = "latest_post_list"

    def get_queryset(self):
        """Return last 5 published posts"""
        return Post.objects.order_by('-published_date')[:5]

class DetailView(generic.DetailView):
    model = Post
    template_name = "notes/detail.html"

class CommentsView(generic.DetailView):
    model = Post
    template_name = "notes/results.html"

class ResultsView(generic.DetailView):
    model = Post
    template_name = "notes/results.html"

def comment(request, post_id):
    p = get_object_or_404(Post, pk=post_id)
    try:
        #selected_comment = p.comment_set.get(pk=request.POST['comment'])
        selected_comment = request.POST['comment']
        print selected_comment
        print post_id
        print p
    except (KeyError, Comment.DoesNotExist):
        return render(request, 'notes/detail.html', {'post': p, 'error_message': "Please select a comment"})
    else:
        #selected_comment.comment_like += 1
        #selected_comment.save()
        return HttpResponseRedirect(reverse('notes:results', args=(p.id,)))

mynote/notes/templates/notes/detail.html
<h1>{{post.post_text}}</h1>
        {% if error_message %}<p><strong>{{error_messge}}</strong></p>{% endif %}

<form action="{% url 'notes:comment' post.id%}" method="post">
    {% csrf_token %}
    <input type="text" name="comment" id="commentid" value="" />
    <label for="commentid">{{comment.comment_text}}</label> <br/>
    <input type="submit" value="Comment">
</form>

<ul>
    {% for comment in post.comment_set.all %}
        <li>{{comment.comment_text}}</li>
    {% endfor %}
</ul>

mynote/notes/templates/notes/index.html
{% if latest_post_list %}
        <ul>
            {% for post in latest_post_list %}
                <li> <a href="{% url 'notes:detail' post.id %}">{{post.post_text}}</a> </li>
            {% endfor %}
        </ul>
{% else %}
        <p> No notes available! </p>
{% endif %}

mynote/notes/templates/notes/results.html
<h1>{{post.post_text}}</h1>

<ul>
    {% for comment in post.comment_set.all %}
        <li>{{comment.comment_text}} -- {{comment.comment_like}} Like{{comment.comment_like|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'notes:detail' post.id %}"> Like again ? </a>